site_name: "The Navi Mumbai Record"
site_description: "Navi Mumbai's Authentic News Source"
site_url: "https://navimumbairecord.com"
language: "en"
navigation:
  - label: "Home"
    url: "/"
  - label: "Latest News"
    url: "/archive.html"
  - label: "Our Journalists"
    url: "/authors.html"
  - label: "About"
    url: "/about.html"
footer_links:
  - label: "Submit a Story"
    url: "/submit.html"
  - label: "Become a Journalist"
    url: "/join.html"
  - label: "RSS Feed"
    url: "/rss.xml"
